download-historical-news:
	./download_historical_news.sh

dataset:
	uv run src/news_sentiment/dataset.py \
    --input_news data/cryptopanic_news.csv \
    --dataset_name news-sentiment-dataset-live \
    --samples 10 \
    --teacher_model claude-sonnet-4-5-20250929